### ISSUE TITLE
[BUG] When waitWhenFinished is used in a job that doesn't create any pods, the job is stuck waiting for default 3h

### ISSUE THREAD

**Issue by smalleni** [cloud-bulldozer/kube-burner#154] opened 2022-02-04 17:55 UTC
**Output of `kube-burner `version**
[smalleni@localhost kubelet-density-medium]$ kube-burner version
Version: 0.14.3
Git Commit: e8c3b246ac1c9dd52936f55e9b0b76d35d6eca32
Build Date: 2021-12-13T19:07:06Z
Go Version: go1.16.11
OS/Arch: linux amd64

**Describe the bug**
When `waitWhenFinished` is used in the spec of a job and the objects created do not create any pods, `waitWhenFinished` is not ignored and the job is stuck waiting for default 3h.

**To Reproduce**
1. Run kube-burner job with `waitWhenFinished` set to `true` and a network policy object that doesn't create any pods

**Expected behavior**
`waitWhenFinished` should be ignored in this case since there are no pods

**Screenshots or output**
```[smalleni@localhost kubelet-density-medium]$ kube-burner init -c kubelet-density-medium.yml 
INFO[2022-02-04 11:48:26] 🔥 Starting kube-burner (0.14.3@e8c3b246ac1c9dd52936f55e9b0b76d35d6eca32) with UUID d8d51f3e-8d0c-4458-b528-4a665b3071ea 
INFO[2022-02-04 11:48:26] 📈 Creating measurement factory               
INFO[2022-02-04 11:48:26] Registered measurement: podLatency           
INFO[2022-02-04 11:48:26] Preparing create job: deny-network-policy    
INFO[2022-02-04 11:48:26] Job deny-network-policy: 1 iterations with 1 NetworkPolicy replicas 
INFO[2022-02-04 11:48:26] Preparing create job: kubelet-density-medium 
INFO[2022-02-04 11:48:26] Job kubelet-density-medium: 100 iterations with 1 Deployment replicas 
INFO[2022-02-04 11:48:26] Job kubelet-density-medium: 100 iterations with 1 Service replicas 
INFO[2022-02-04 11:48:26] Job kubelet-density-medium: 100 iterations with 1 Deployment replicas 
INFO[2022-02-04 11:48:26] Triggering job: deny-network-policy          
INFO[2022-02-04 11:48:27] Creating Pod latency informer for deny-network-policy 
INFO[2022-02-04 11:48:27] QPS: 1                                       
INFO[2022-02-04 11:48:27] Burst: 1                                     
INFO[2022-02-04 11:48:27] Running job deny-network-policy              
INFO[2022-02-04 11:48:27] Waiting 3h0m0s for actions to be completed   
```

**Comment by smalleni** [comment] 2022-02-04 17:56
@rsevilla87 thoughts?

**Comment by rsevilla87** [comment] 2022-02-06 21:21
> @rsevilla87 thoughts?

Yeah, seems a bug. My first suggestion is to set waitWhenFinished to false in this case. Needs a fix though.

**Comment by smalleni** [comment] 2022-02-07 01:00
> > @rsevilla87 thoughts?
> 
> Yeah, seems a bug. My first suggestion is to set waitWhenFinished to false in this case. Needs a fix though.

Yep, that's what I did but wanted to open an issue to track it.

**Comment by rsevilla87** [comment] 2022-02-07 10:21
Curious, Im not able to reproduce the issue 🤔 
```
$ kube-burner version
Version: v0.14.2
Git Commit: 35fb3d9c697eb50fb055c175ad546154dcaa4dd3
Build Date: 2022-02-07-11:20:44
Go Version: go1.16.13
OS/Arch: linux amd64


INFO[2022-02-07 11:18:51] 🔥 Starting kube-burner (latest@35fb3d9c697eb50fb055c175ad546154dcaa4dd3) with UUID ae035d97-2fec-49ae-a9e5-c6691dbca250 
INFO[2022-02-07 11:18:51] 📈 Creating measurement factory               
INFO[2022-02-07 11:18:51] Registered measurement: podLatency           
INFO[2022-02-07 11:18:51] Preparing create job: deny-all-policy        
INFO[2022-02-07 11:18:51] Job deny-all-policy: 1 iterations with 1 NetworkPolicy replicas 
INFO[2022-02-07 11:18:51] Triggering job: deny-all-policy              
INFO[2022-02-07 11:18:51] Deleting namespaces with label kube-burner-job=deny-all-policy 
INFO[2022-02-07 11:18:52] Waiting for namespaces to be definitely deleted 
INFO[2022-02-07 11:18:58] Creating Pod latency informer for deny-all-policy 
INFO[2022-02-07 11:18:58] QPS: 1                                       
INFO[2022-02-07 11:18:58] Burst: 1                                     
INFO[2022-02-07 11:18:58] Running job deny-all-policy                  
INFO[2022-02-07 11:18:58] Waiting 3h0m0s all job actions to be completed 
INFO[2022-02-07 11:18:58] Actions in namespace kubelet-density-cni-networkpolicy completed 
INFO[2022-02-07 11:18:58] Verifying created objects                    
INFO[2022-02-07 11:18:59] networkpolicies found: 1 Expected: 1         
INFO[2022-02-07 11:18:59] Stopping measurement: podLatency             
INFO[2022-02-07 11:18:59] Evaluating latency thresholds                
INFO[2022-02-07 11:18:59] Writing pod latency metrics in collected-metrics/deny-all-policy-podLatency.json 
INFO[2022-02-07 11:18:59] Writing pod latency metrics in collected-metrics/deny-all-policy-podLatency-summary.json 
INFO[2022-02-07 11:18:59] Job deny-all-policy took 7.38 seconds        
INFO[2022-02-07 11:18:59] Finished execution with UUID: ae035d97-2fec-49ae-a9e5-c6691dbca250 
INFO[2022-02-07 11:18:59] 👋 Exiting kube-burner  
```

Can you double check it @smalleni

**Comment by rsevilla87** [comment] 2022-02-07 19:00
Closing it then, if we see it in the future we can reopen with a clear reproducer.

**Closed by rsevilla87** 2022-02-07 19:00 UTC
Labels: bug
