### ISSUE TITLE
Allow export results to a file without a Prometheus Endpoint

### ISSUE THREAD

**Issue by evafp90** [cloud-bulldozer/kube-burner#270] opened 2023-03-13 16:02 UTC
**Is your feature request related to a problem? Please describe.**
After this [PR](https://github.com/cloud-bulldozer/kube-burner/commit/c5353b35bc48fa9d71bb1b53638c54850e399966) were merged, it is not possible to create tarball locally without adding a prometheus or alerting endpoint explicitly from the CLI.

**Describe the solution you'd like**
Be able to write the results of the tests on a file, without a Prometheus endpoint, just like it used to work. 

**Describe alternatives you've considered**

**Additional context**

**Comment by rsevilla87** [comment] 2023-03-15 10:31
Hey!, thanks for reporting, can you paste an output of the issue?

**Comment by rsevilla87** [comment] 2023-03-15 11:02
I couldn't reproduce the issue with the latest v1.4.3 version using the following configuration:


```yaml
global:
  indexerConfig:
    enabled: true
    type: local
    createTarball: true
  measurements:
    - name: podLatency
      thresholds:
      - conditionType: Ready
        metric: Avg
        threshold: 4s
jobs:
  - name: example
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    preLoadImages: false
    namespace: example
    waitWhenFinished: true
    podWait: false
    objects:

      - objectTemplate: templates/pod.yml
        replicas: 1
```

And the metrics-profile:

```yaml
- query: sum by (cluster_version)(etcd_cluster_version)
  metricName: etcdVersion
```


```shell
$ kube-burner init -c example.yml  -u=<truncated> --token=$TOKEN -m metrics.yml                                              
INFO[2023-03-15 11:51:21] 📁 Creating indexer: local                    
INFO[2023-03-15 11:51:21] 👽 Initializing prometheus client with URL: https://prometheus-k8s-openshift-monitoring.apps.hs-mc-0vfs0e6gg.iau9.s1.devshift.org 
INFO[2023-03-15 11:51:23] 🔥 Starting kube-burner (v1.4.3@a575df584a6b520a45e2fe7903e608a34e722e5f) with UUID af75b667-85d6-4a62-9bfe-b8343db758d4 
INFO[2023-03-15 11:51:23] 📈 Creating measurement factory               
INFO[2023-03-15 11:51:23] Registered measurement: podLatency           
INFO[2023-03-15 11:51:23] Job example: 1 iterations with 1 Pod replicas 
INFO[2023-03-15 11:51:23] QPS: 20                                      
INFO[2023-03-15 11:51:23] Burst: 20                                    
INFO[2023-03-15 11:51:23] Triggering job: kubelet-density   
INFO[2023-03-15 11:51:38] Creating Pod latency watcher for kubelet-density
INFO[2023-03-15 11:51:41] Running job kubelet-density
INFO[2023-03-15 11:51:42] Waiting up to 3h0m0s for actions to be completed 
INFO[2023-03-15 11:51:45] Actions in namespace kubelet-density completed 
INFO[2023-03-15 11:51:45] Finished the create job in 3s                
INFO[2023-03-15 11:51:45] Verifying created objects                    
INFO[2023-03-15 11:51:45] pods found: 1 Expected: 1                    
INFO[2023-03-15 11:51:45] Stopping measurement: podLatency             
INFO[2023-03-15 11:51:45] Evaluating latency thresholds                
INFO[2023-03-15 11:51:45] Indexing pod latency data for job: kubelet-density 
INFO[2023-03-15 11:51:45] Writing metric to: collected-metrics/podLatencyMeasurement-kubelet-density.json 
INFO[2023-03-15 11:51:45] Writing metric to: collected-metrics/podLatencyQuantilesMeasurement-kubelet-density.json 
INFO[2023-03-15 11:51:45] kubelet-density: PodScheduled 50th: 0 99th: 0 max: 0 avg: 0 
INFO[2023-03-15 11:51:45] kubelet-density: ContainersReady 50th: 0 99th: 0 max: 0 avg: 1791 
INFO[2023-03-15 11:51:45] kubelet-density: Initialized 50th: 0 99th: 0 max: 0 avg: 0 
INFO[2023-03-15 11:51:45] kubelet-density: Ready 50th: 0 99th: 0 max: 0 avg: 1791 
INFO[2023-03-15 11:51:45] Job kubelet-density took 22.56 seconds       
INFO[2023-03-15 11:51:45] Writing metric to: collected-metrics/jobSummary-example.json 
INFO[2023-03-15 11:51:45] Waiting 30s extra before scraping prometheus endpoints
INFO[2023-03-15 11:52:15] Scraping for the prometheus entry with params - Endpoint: <truncated>, Profile: metrics.yml, Start: 2023-03-15T10:51:23Z, End: 2023-03-15T10:51:45Z 
INFO[2023-03-15 11:52:15] Indexing metrics with UUID af75b667-85d6-4a62-9bfe-b8343db758d4 
INFO[2023-03-15 11:52:15] 🔍 Scraping prometheus metrics for benchmark from 2023-03-15T10:51:23Z to 2023-03-15T10:51:45Z 
INFO[2023-03-15 11:52:20] Writing metric to: collected-metrics/etcdVersion.json 
INFO[2023-03-15 11:52:22] Metrics tarball generated at kube-burner-metrics.tgz 
INFO[2023-03-15 11:52:22] Finished execution with UUID: af75b667-85d6-4a62-9bfe-b8343db758d4 
INFO[2023-03-15 11:52:22] 👋 Exiting kube-burner af75b667-85d6-4a62-9bfe-b8343db758d4 
$ ls -lh kube-burner-metrics.tgz 
-rw-r--r--. 1 rsevilla rsevilla 1K Mar 15 11:52 kube-burner-metrics.tgz   # Tarball is in the same directory
```

I did some tests using the subcommand `index` with similar success as well.

Keep in mind that we recently merged some changes that affect the configuration file schema:

https://github.com/cloud-bulldozer/kube-burner/pull/259

With this change, the variable writeToFile has been deprecated and its behavior has been moved to the indexerConfig section. You can find updated info in the [indexers section of the docs site](https://kube-burner.readthedocs.io/en/latest/indexers/#local)


Last but not least, make sure to always use a tagged kube-burner version if possible if you're not already doing it.
https://github.com/cloud-bulldozer/kube-burner/releases

**Closed** 2023-03-30 09:39 UTC
Labels: bug
