### ISSUE TITLE
[BUG] Unable to create a NetworkAttachmentDefinition resource from kube burner

### ISSUE THREAD

**Issue by josecastillolema** [cloud-bulldozer/kube-burner#324] opened 2023-05-25 08:11 UTC
I am trying to create a **NetworkAttachmentDefinition** resource using Kube-burner.
Below is the job item:
```
  - name: create-networks-job
    jobType: create
    jobIterations: 1
    qps: 10
    burst: 10
    namespacedIterations: true
    cleanup: false
    namespace: serving-ns
    podWait: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 1s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: objectTemplates/macvlan_network.yml
        replicas: 1
```

```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net
  namespace: serving-ns-1
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "internal-net",
      "plugins": [
        {
          "type": "macvlan",
          "master": "breth0",
          "mode": "bridge",
          "ipam": {
            "type": "static"
          }
        },
        {
          "capabilities": {
            "mac": true,
            "ips": true
          },
          "type": "tuning"
        }
      ]
    }
```

But the creation fails with the error:
```
ERRO[2023-05-23 18:09:28] Error creating object NetworkAttachmentDefinition/sriov-net-1 in namespace serving-ns-1: the server could not find the requested resource 
```

Manually creating the resource works, i.e.: `kubectl apply -f macvlan_network.yml`

Kube-burner version 1.6 (tested 1.3 as well).

**Comment by rsevilla87** [comment] 2023-05-26 08:30
I managed to reproduce it locally too, I haven't found a fix for this issue though.
It seems like the discovered gvr for NetworkAttachDeffinitions is not correct.

https://github.com/cloud-bulldozer/kube-burner/blob/be7b493d6b6f9301525a329133117f101ffc3eeb/pkg/burner/create.go#LL76C18-L76C43


The root of the issue is that the object Kind is `NetworkAttachmentDefinition` and the previous function returns `networkattachmentdefinitions`. The implementation of `UnsafeGuessKindToResource`  is unsafe and it has some exceptions like this one. It should have returned `network-attachment-definitions` (with dashes), as per api-resources return.

```shell
$ oc api-resources | grep network-attachment
network-attachment-definitions        net-attach-def      k8s.cni.cncf.io/v1                            true         NetworkAttachmentDefinition
```

I have to look for alternatives for `UnsafeGuessKindToResource`

**Comment by rsevilla87** [comment] 2023-05-29 19:08
Seems like we can shift from `UnsafeGuessKindToResource()` to `ServerResourcesForGroupVersion()` or `ServerGroupsAndResources()`, available in `ClientSet.DiscoveryClient`.

I'll go over it in the next days.

**Closed** 2023-06-02 13:52 UTC
Labels: bug
